/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsSlugRouteImport } from './routes/tests.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as TestsSlugResultRouteImport } from './routes/tests.$slug.result'
import { Route as TestsSlugAttemptRouteImport } from './routes/tests.$slug.attempt'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsSlugRoute = TestsSlugRouteImport.update({
  id: '/tests/$slug',
  path: '/tests/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TestsSlugResultRoute = TestsSlugResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => TestsSlugRoute,
} as any)
const TestsSlugAttemptRoute = TestsSlugAttemptRouteImport.update({
  id: '/attempt',
  path: '/attempt',
  getParentRoute: () => TestsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/subjects': typeof SubjectsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/tests/$slug': typeof TestsSlugRouteWithChildren
  '/tests/$slug/attempt': typeof TestsSlugAttemptRoute
  '/tests/$slug/result': typeof TestsSlugResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/subjects': typeof SubjectsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/tests/$slug': typeof TestsSlugRouteWithChildren
  '/tests/$slug/attempt': typeof TestsSlugAttemptRoute
  '/tests/$slug/result': typeof TestsSlugResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/subjects': typeof SubjectsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/tests/$slug': typeof TestsSlugRouteWithChildren
  '/tests/$slug/attempt': typeof TestsSlugAttemptRoute
  '/tests/$slug/result': typeof TestsSlugResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/subjects'
    | '/admin'
    | '/tests/$slug'
    | '/tests/$slug/attempt'
    | '/tests/$slug/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/subjects'
    | '/admin'
    | '/tests/$slug'
    | '/tests/$slug/attempt'
    | '/tests/$slug/result'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/subjects'
    | '/_authenticated/admin'
    | '/tests/$slug'
    | '/tests/$slug/attempt'
    | '/tests/$slug/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SubjectsRoute: typeof SubjectsRoute
  TestsSlugRoute: typeof TestsSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$slug': {
      id: '/tests/$slug'
      path: '/tests/$slug'
      fullPath: '/tests/$slug'
      preLoaderRoute: typeof TestsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/tests/$slug/result': {
      id: '/tests/$slug/result'
      path: '/result'
      fullPath: '/tests/$slug/result'
      preLoaderRoute: typeof TestsSlugResultRouteImport
      parentRoute: typeof TestsSlugRoute
    }
    '/tests/$slug/attempt': {
      id: '/tests/$slug/attempt'
      path: '/attempt'
      fullPath: '/tests/$slug/attempt'
      preLoaderRoute: typeof TestsSlugAttemptRouteImport
      parentRoute: typeof TestsSlugRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TestsSlugRouteChildren {
  TestsSlugAttemptRoute: typeof TestsSlugAttemptRoute
  TestsSlugResultRoute: typeof TestsSlugResultRoute
}

const TestsSlugRouteChildren: TestsSlugRouteChildren = {
  TestsSlugAttemptRoute: TestsSlugAttemptRoute,
  TestsSlugResultRoute: TestsSlugResultRoute,
}

const TestsSlugRouteWithChildren = TestsSlugRoute._addFileChildren(
  TestsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SubjectsRoute: SubjectsRoute,
  TestsSlugRoute: TestsSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
